version: "3"
services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:4.2.5
    volumes:
      - data1:/data/db
    networks:
      - mongo-net
    expose:
      - 30001
    ports:
      - 30001:30001
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "30001", "--replSet", "rs01", "--oplogSize", "128" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:4.2.5
    volumes:
      - data2:/data/db
    networks:
      - mongo-net
    expose:
      - 30002
    ports:
      - 30002:30002
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "30002", "--replSet", "rs01", "--oplogSize", "128" ]
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:4.2.5
    volumes:
      - data3:/data/db
    networks:
      - mongo-net
    expose:
      - 30003
    ports:
      - 30003:30003
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--port", "30003", "--replSet", "rs01", "--oplogSize", "128" ]

networks:
  mongo-net:

volumes:
  data1:
  data2:
  data3: